sudo: false

language: go

go:
  - "1.13"

install: true
script:
  - echo "baetyl-go unit test begin"
  - env GO111MODULE=on GOPROXY=https://goproxy.cn make test GO_TEST_FLAGS=--race
  - echo "baetyl-go unit test end"
