function:
  address: https://baetyl-function:8880
broker:
  address: ssl://baetyl-broker:8883
cert:
  ca: example/var/lib/baetyl/testcert/ca.pem
  key: example/var/lib/baetyl/testcert/client.key
  cert: example/var/lib/baetyl/testcert/client.pem
logger:
  filename: "var/log/service.log"
  level: "debug"
  encoding: "console"
