// Code generated by protoc-gen-go. DO NOT EDIT.
// source: link.proto

package link

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Context              *Context `protobuf:"bytes,1,opt,name=Context,proto3" json:"Context,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee656911eb8a56a, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Context struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TS                   uint64   `protobuf:"varint,2,opt,name=TS,proto3" json:"TS,omitempty"`
	QOS                  uint32   `protobuf:"varint,3,opt,name=QOS,proto3" json:"QOS,omitempty"`
	Flags                uint32   `protobuf:"varint,4,opt,name=Flags,proto3" json:"Flags,omitempty"`
	Topic                string   `protobuf:"bytes,5,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Src                  string   `protobuf:"bytes,6,opt,name=Src,proto3" json:"Src,omitempty"`
	Dest                 string   `protobuf:"bytes,7,opt,name=Dest,proto3" json:"Dest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee656911eb8a56a, []int{1}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Context) GetTS() uint64 {
	if m != nil {
		return m.TS
	}
	return 0
}

func (m *Context) GetQOS() uint32 {
	if m != nil {
		return m.QOS
	}
	return 0
}

func (m *Context) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Context) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Context) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Context) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "link.Message")
	proto.RegisterType((*Context)(nil), "link.Context")
}

func init() { proto.RegisterFile("link.proto", fileDescriptor_2ee656911eb8a56a) }

var fileDescriptor_2ee656911eb8a56a = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9d, 0x74, 0xda, 0xe0, 0x68, 0x45, 0x06, 0x0f, 0x83, 0xa7, 0x90, 0x83, 0x2e, 0x1e,
	0x8a, 0xd4, 0x47, 0x68, 0x10, 0x0a, 0x15, 0x71, 0x93, 0x93, 0xb7, 0x58, 0x42, 0x09, 0x59, 0x92,
	0xd2, 0xec, 0xc1, 0x97, 0xf0, 0x9d, 0x65, 0xa7, 0x5b, 0xc1, 0x53, 0x6f, 0xff, 0xf7, 0xed, 0x3f,
	0x03, 0xb3, 0x44, 0xae, 0xed, 0xbb, 0xc5, 0xfe, 0x30, 0xf8, 0x81, 0x31, 0xe4, 0x7c, 0x43, 0xe9,
	0x5b, 0x33, 0x8e, 0xf5, 0xae, 0xe1, 0x47, 0x4a, 0x57, 0x43, 0xef, 0x9b, 0x6f, 0x2f, 0x90, 0x81,
	0xb9, 0x5a, 0xce, 0x17, 0x5a, 0x8f, 0xd2, 0x9e, 0x5e, 0x59, 0x62, 0xb1, 0xf7, 0x92, 0x64, 0x60,
	0xae, 0xed, 0x09, 0xf3, 0x1f, 0xf8, 0xdb, 0xc1, 0x37, 0x94, 0xac, 0x0b, 0xdd, 0x84, 0x36, 0x59,
	0x17, 0x81, 0xab, 0x52, 0x07, 0xd0, 0x26, 0x55, 0xc9, 0xb7, 0x34, 0xf9, 0x78, 0x2f, 0x65, 0x92,
	0x81, 0x99, 0xdb, 0x10, 0xf9, 0x8e, 0xa6, 0xaf, 0xae, 0xde, 0x8d, 0x82, 0xea, 0x8e, 0x10, 0x6c,
	0x35, 0xec, 0xdb, 0xad, 0x4c, 0x33, 0x30, 0x97, 0xf6, 0x08, 0x61, 0xba, 0x3c, 0x6c, 0x65, 0xa6,
	0x2e, 0x44, 0x66, 0xc2, 0xa2, 0x19, 0xbd, 0xa4, 0xaa, 0x34, 0x2f, 0x3f, 0x09, 0x37, 0x6d, 0xdf,
	0xf1, 0x13, 0x61, 0x55, 0xbb, 0x8e, 0xe3, 0x45, 0xf1, 0xe2, 0xfb, 0xff, 0x98, 0x5f, 0x18, 0x78,
	0x06, 0x7e, 0x20, 0x5c, 0xd5, 0xce, 0x9d, 0xeb, 0x7e, 0xcd, 0xf4, 0x1b, 0x5f, 0x7e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x99, 0xde, 0xcb, 0x3f, 0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkClient interface {
	Talk(ctx context.Context, opts ...grpc.CallOption) (Link_TalkClient, error)
	Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type linkClient struct {
	cc *grpc.ClientConn
}

func NewLinkClient(cc *grpc.ClientConn) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Talk(ctx context.Context, opts ...grpc.CallOption) (Link_TalkClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Link_serviceDesc.Streams[0], "/link.Link/Talk", opts...)
	if err != nil {
		return nil, err
	}
	x := &linkTalkClient{stream}
	return x, nil
}

type Link_TalkClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type linkTalkClient struct {
	grpc.ClientStream
}

func (x *linkTalkClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *linkTalkClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *linkClient) Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/link.Link/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
type LinkServer interface {
	Talk(Link_TalkServer) error
	Call(context.Context, *Message) (*Message, error)
}

// UnimplementedLinkServer can be embedded to have forward compatible implementations.
type UnimplementedLinkServer struct {
}

func (*UnimplementedLinkServer) Talk(srv Link_TalkServer) error {
	return status.Errorf(codes.Unimplemented, "method Talk not implemented")
}
func (*UnimplementedLinkServer) Call(ctx context.Context, req *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterLinkServer(s *grpc.Server, srv LinkServer) {
	s.RegisterService(&_Link_serviceDesc, srv)
}

func _Link_Talk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LinkServer).Talk(&linkTalkServer{stream})
}

type Link_TalkServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type linkTalkServer struct {
	grpc.ServerStream
}

func (x *linkTalkServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *linkTalkServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Link_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link.Link/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Call(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Link_serviceDesc = grpc.ServiceDesc{
	ServiceName: "link.Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Link_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Talk",
			Handler:       _Link_Talk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "link.proto",
}
